---
- name:  Lab
  hosts: ec2
  become: true
  vars_files:
  - vars.yml
  tasks:
    - name: Add Docker Repository
      yum_repository:
        name: docker_repo
        description: docker_repo
        baseurl: deb https://download.docker.com/linux/ubuntu bionic stable
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install a list of packages
      yum:
        pkg:
        - python3-pip
        - docker
        state: latest
        update_cache: yes     

    - name: Install Docker Module for Python
      pip: 
        name: docker

    - name: Ensure service is enabled
      command: service docker restart    
     
    - name: Start docker container 
      docker_container:
        name: docker_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
        - "3306:3306"       
        state: started
        env:
          MYSQL_ROOT_PASSWORD: '{{ mysql_pass }}'
          MYSQL_ROOT_HOST: '%'
      tags:
      - sql 

    - name: Pause docker network up
      pause:
        seconds: 10       

    - name: Create database
      mysql_db:
        name: newbases1
        login_host: ec2-3-87-158-93.compute-1.amazonaws.com
        login_user: '{{ username }}'
        login_password: '{{ mysql_pass }}'   
        state: present
      delegate_to: 127.0.0.1
      become: no
      tags: 
      - base

  
    
    
    
   

    