---
- name:  Lab
  hosts: ubuntu
  become: true
  vars_files:
  - vars.yml
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install required system packages
      apt: 
        pkg:
        - apt-transport-https
        - software-properties-common
        - python3-pip
        - docker-ce
        state: latest
        update_cache: yes
     
    - name: Install Docker Module for Python
      pip: 
        name: docker
     
    - name: Start docker container 
      docker_container:
        name: docker_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
        - "3306:3306"       
        state: started
        env:
          MYSQL_ROOT_PASSWORD: '{{ mysql_pass }}'
          MYSQL_ROOT_HOST: '%'
      tags:
        - sql 

    - name: Pause docker network up
      pause:
        seconds: 10       

    - name: Create database
      mysql_db:
        name: newbases1
        login_host: 172.16.90.130
        login_user: '{{ username }}'
        login_password: '{{ mysql_pass }}'   
        state: present
      delegate_to: 127.0.0.1
      become: no
      tags: 
      - base

  
    
    
    
   

    
